[package]
name = "benchmark"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { version = "0.7" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
